default: &default
  adapter: postgresql
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: slashum_development

test:
  <<: *default
  database: slashum_test

production:
  <<: *default
  host: db
  port: 5432
  database: slashum_production
  username: postgres
  password: <%= ENV["DB_ENV_POSTGRES_PASSWORD"] %>
