default: &default
  adapter: postgresql
  timeout: 5000
  pool: 2

development:
  <<: *default
  database: slashum_development

test:
  <<: *default
  database: slashum_test

production:
  <<: *default
  host: <%= ENV["DB_PORT_5432_TCP_ADDR"] %>
  port: <%= ENV["DB_PORT_5432_TCP_PORT"] %>
  database: slashum_production
  username: postgres
  password: <%= ENV["DB_ENV_POSTGRES_PASSWORD"] %>
